{% set version = "2.2.1" %}

package:
  name: muscat-split
  version: {{ version }}


source:
  url: https://gitlab.com/drti/muscat/-/archive/{{ version }}/muscat-{{ version }}.tar.bz2
  sha256: a11d9b8471f897d64e8b14a1af5d537dce5be9b75d14d17a691b623b7367d7b6

build:
  number: 1

outputs:
  - name: muscat-core
    version: {{ version }}
    script: build_core.sh  # [not win]
    script: bld_core.bat  # [win]
    build:
      entry_points:
        - "MeshFileConvert = Muscat.IO.MeshFileConverter:Main"
      skip_compile_pyc:
        "MuscatParaViewPlugin.py"

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - ninja                                  # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
      host:
        - python
        - numpy
        - cython
        - sympy
        - eigency
        - mkl
        - mkl-include
        - setuptools-scm
        - eigen
        - libboost-headers
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
        - pip
        - tbb
        - tbb-devel
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.9
        - sympy
        - eigency
        - mkl
        - networkx >=3.0
        - tbb
        - dill
        - pywin32  # [win]
    test:
      imports:
        - Muscat
      commands:
        - python -u -m Muscat.Helpers.Check -k Which  # [osx]
        - python -u -m Muscat.Helpers.Check  # [not osx]

  - name: "muscat-extensions"
    version: {{ version }}
    requirements:
      host:
        - python
        - numpy
        - vtk
        - psutil
        - h5py
        - meshio
        - pyvista
        - networkx >=3.0
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - vtk
        - psutil
        - h5py
        - meshio
        - pyvista
        - networkx >=3.0
        - mmgsuite  # [not win]
    test:
      imports:
        - psutil
        - h5py
        - meshio
        - networkx

  - name: "muscat"
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage('muscat-core', max_pin='x.x.x') }}
        - {{ pin_subpackage('muscat-extensions', max_pin='x.x.x') }}
    test:
      imports:
        - Muscat
      commands:
        - python -u -m Muscat.Helpers.Check -k Which  # [osx]
        - python -u -m Muscat.Helpers.Check  # [not osx]

  - name: "muscat-devenv"
    version: {{ version }}
    requirements:
      run:
        - {{ compiler('cxx') }}
        - python
        - numpy
        - sympy
        - cython
        - eigency
        - mkl
        - mkl-include
        - setuptools-scm
        - eigen
        - scipy >=1.9
        - h5py
        - pycgns
        - networkx >=3.0
        - libboost-headers
        - pytest
        - vtk
        - tbb
        - tbb-devel
        - matplotlib
        - coverage
        - pywin32  # [win]
    test:
      imports:
        - numpy

about:
  home: https://gitlab.com/drti/muscat
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Tools for finite element computations

extra:
  recipe-maintainers:
    - fbordeu
